services:
  base:
    image: qmkfm/qmk_firmware:${QMK_FIRMWARE_VERSION}
    user: ${UID}:${GID}
    working_dir: /qmk_firmware
    volumes:
      - type: bind
        source: .
        target: /qmk_firmware
    command: ["qmk", "--version"]

  bmp:
    extends:
      service: base
    command: ["make", "ble_micro_pro:r-okm:uf2"]

  crkbd:
    extends:
      service: base
    command: ["qmk", "compile", "-kb", "crkbd", "-km", "r-okm"]
