services:
  base:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - UID
        - GID
    image: r-okm/qmk_firmware:latest
    volumes:
      - type: bind
        source: .
        target: /home/qmk/work
    command: ["bash"]

  bmp:
    extends:
      service: base
    command: ["make", "ble_micro_pro:r-okm:uf2"]

  crkbd:
    extends:
      service: base
    command: ["qmk", "compile", "-kb", "crkbd", "-km", "r-okm"]
