services:
  bmp:
    image: qmkfm/qmk_firmware
    working_dir: /work
    volumes:
      - type: bind
        source: .
        target: /work
    command: ["make", "ble_micro_pro:r-okm:uf2"]

  crkbd:
    image: qmkfm/qmk_firmware
    working_dir: /work
    volumes:
      - type: bind
        source: .
        target: /work
    command: ["qmk", "compile", "-kb", "crkbd", "-km", "r-okm"]
