version: "3.8"

services:
    compile:
        image: qmkfm/qmk_firmware
        working_dir: /work
        volumes:
            - .:/work
        command: ["/bin/sh", "-c", "make ${KEYBOARD}:${PROFILE}:uf2"]
