services:
  bmp:
    image: qmkfm/qmk_firmware
    working_dir: /work
    volumes:
      - .:/work
    command: /bin/sh -c "make ble_micro_pro:r-okm:uf2"

  crkbd:
    image: qmkfm/qmk_firmware
    working_dir: /work
    volumes:
      - .:/work
    command: /bin/sh -c "qmk compile -kb crkbd -km r-okm"
