name: Build default firmware for BLE Micro Pro

on:
  push:
    branches: [dev/ble_micro_pro]
  pull_request:
    branches: [dev/ble_micro_pro]

  workflow_dispatch:

env:
  TAG_NAME: latest

jobs:
  build:
    runs-on: ubuntu-latest
    container: qmkfm/qmk_firmware

    steps:
      - name: Set short SHA
        run: echo "SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Build ble_micro_pro firmware
        run: make ble_micro_pro:r-okm:uf2

      - name: Upload artifact
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        with:
          name: Firmware_${{ env.SHORT_SHA }}
          path: ./*.uf2

  publish:
    runs-on: ubuntu-latest
    if: github.ref_name == 'dev/ble_micro_pro' && !cancelled()
    needs: build
    permissions:
      contents: write
    steps:
      - name: Set short SHA
        run: echo "SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV

      - name: Download binaries
        if: always() && !cancelled()
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
        with:
          name: Firmware_${{ env.SHORT_SHA }}

      - name: Delete release
        run: gh release delete ${{ env.TAG_NAME }} --cleanup-tag || true
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Generate Release
        uses: softprops/action-gh-release@a06a81a03ee405af7f2048a818ed3f03bbf83c7b # v2.5.0
        if: always() && !cancelled()
        with:
          token: ${{ github.token }}
          name: QMK Firmware
          tag_name: ${{ env.TAG_NAME }}
          fail_on_unmatched_files: false
          draft: false
          prerelease: false
          files: ./*.uf2
